name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: fullstack_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Build Docker images
        run: |
          docker build -t monapp-backend ./backend
          docker build -t monapp-frontend ./frontend

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push images to Docker Hub
        run: |
          docker tag monapp-backend docker.io/${{ secrets.DOCKER_USERNAME }}/monapp-backend
          docker tag monapp-frontend docker.io/${{ secrets.DOCKER_USERNAME }}/monapp-frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/monapp-backend
          docker push ${{ secrets.DOCKER_USERNAME }}/monapp-frontend
